"""Generated-tree enforcement.

Acceptance criterion `02a` §−2.3 `WP-BOOT-02` ⑤ — `registry/build/**` is
`GENERATED` (`06` §3.3), so a hand edit must be rejected. `--check` regenerates
into memory and compares, which is the only form of that rule an unattended
pipeline can act on.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from registry.generate.cli import INDEX_FILENAMES, check, main, owned_paths, render_all, write
from registry.generate.manifests import MANIFEST_SUBDIR
from registry.generate.source import REGISTRY_PATH

REGISTRY = Path(__file__).resolve().parents[2] / REGISTRY_PATH


@pytest.fixture
def build_dir(tmp_path: Path) -> Path:
    """Materialize a freshly generated tree.

    Args:
        tmp_path: pytest-provided scratch directory.

    Returns:
        Path: Root of the generated tree.
    """
    target = tmp_path / "build"
    write(target, render_all(REGISTRY))
    return target


def test_freshly_generated_tree_is_clean(build_dir: Path) -> None:
    """A tree written by the generator reports no divergence."""
    assert check(build_dir, render_all(REGISTRY)) == []


def test_hand_edited_manifest_is_rejected(build_dir: Path) -> None:
    """Editing a generated manifest by hand is caught."""
    target = build_dir / MANIFEST_SUBDIR / "WP-BOOT-02.json"
    manifest = json.loads(target.read_text(encoding="utf-8"))
    manifest["exec_class"] = "AI-on-HW"
    target.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    findings = check(build_dir, render_all(REGISTRY))
    assert findings == [f"differs from generated output: {MANIFEST_SUBDIR}/WP-BOOT-02.json"]


@pytest.mark.parametrize("name", INDEX_FILENAMES)
def test_hand_edited_index_is_rejected(build_dir: Path, name: str) -> None:
    """Editing any generated index by hand is caught."""
    target = build_dir / name
    target.write_text(target.read_text(encoding="utf-8").replace("\n", "\n ", 1), encoding="utf-8")
    assert check(build_dir, render_all(REGISTRY)) == [f"differs from generated output: {name}"]


def test_whitespace_only_edit_is_rejected(build_dir: Path) -> None:
    """Byte comparison catches an edit that leaves the JSON value unchanged."""
    target = build_dir / MANIFEST_SUBDIR / "WP-BOOT-02.json"
    target.write_text(target.read_text(encoding="utf-8") + "\n", encoding="utf-8")
    assert check(build_dir, render_all(REGISTRY)) != []


def test_deleted_file_is_rejected(build_dir: Path) -> None:
    """A generated file removed from the tree is reported as missing."""
    (build_dir / "gate_index.json").unlink()
    assert check(build_dir, render_all(REGISTRY)) == ["missing: gate_index.json"]


def test_hand_added_manifest_is_rejected(build_dir: Path) -> None:
    """A manifest the current registry does not produce is reported."""
    (build_dir / MANIFEST_SUBDIR / "WP-0C-99.json").write_text("{}\n", encoding="utf-8")
    findings = check(build_dir, render_all(REGISTRY))
    assert findings == [f"not generated by the current registry: {MANIFEST_SUBDIR}/WP-0C-99.json"]


def test_regeneration_removes_a_no_longer_generated_file(build_dir: Path) -> None:
    """Regenerating drops artefacts the current registry no longer produces."""
    stray = build_dir / MANIFEST_SUBDIR / "WP-0C-99.json"
    stray.write_text("{}\n", encoding="utf-8")
    removed = write(build_dir, render_all(REGISTRY))
    assert removed == [f"{MANIFEST_SUBDIR}/WP-0C-99.json"]
    assert not stray.exists()


def test_foreign_artefacts_are_left_alone(build_dir: Path) -> None:
    """Files owned by other bootstrap packages are neither checked nor deleted.

    `registry/build/` also holds `WP-BOOT-01`'s reconciliation report and the
    `CI-04b` evidence trees. Judging them here would put one generator in
    charge of another's output.
    """
    foreign = build_dir / "reconciliation.md"
    foreign.write_text("owned by WP-BOOT-01\n", encoding="utf-8")
    evidence = build_dir / "evidence" / "CG-BOOT-02a" / "note.txt"
    evidence.parent.mkdir(parents=True)
    evidence.write_text("owned by the accepting package\n", encoding="utf-8")

    assert check(build_dir, render_all(REGISTRY)) == []
    write(build_dir, render_all(REGISTRY))
    assert foreign.exists()
    assert evidence.exists()
    assert "reconciliation.md" not in owned_paths(build_dir)


def test_main_regenerates_then_verifies(tmp_path: Path) -> None:
    """The command writes a tree and then confirms it, returning success."""
    target = tmp_path / "build"
    arguments = ["--registry", str(REGISTRY), "--build-dir", str(target)]
    assert main(arguments) == 0
    assert main([*arguments, "--check"]) == 0


def test_main_fails_the_build_on_a_hand_edit(tmp_path: Path) -> None:
    """The command exits non-zero when the tree diverges."""
    target = tmp_path / "build"
    arguments = ["--registry", str(REGISTRY), "--build-dir", str(target)]
    main(arguments)
    (target / "req_index.json").write_text("{}\n", encoding="utf-8")
    assert main([*arguments, "--check"]) == 1


def test_main_fails_when_the_tree_is_absent(tmp_path: Path) -> None:
    """Checking a tree that was never generated fails rather than passing vacuously."""
    arguments = ["--registry", str(REGISTRY), "--build-dir", str(tmp_path / "nothing"), "--check"]
    assert main(arguments) == 1
