"""Index determinism and the requirement/work-package inverse.

Acceptance criteria `02a` §−2.3 `WP-BOOT-02` ③ (the five indexes regenerate
deterministically: same input gives the same bytes, one changed bit gives
different bytes) and ④ (`req_index` and `wp_index` are mutual inverses, and a
fixture where only one direction holds is rejected).
"""

from __future__ import annotations

import copy
import json
from typing import Any

import pytest

from registry.generate.indexes import (
    build_contract_index,
    build_gate_index,
    build_glob_index,
    build_req_index,
    build_wp_index,
    check_index_inverse,
    render_indexes,
)
from registry.generate.source import (
    Record,
    WorkPackage,
    group_by_work_package,
    registry_digest,
)

INDEX_FILENAMES = (
    "req_index.json",
    "wp_index.json",
    "glob_index.json",
    "contract_index.json",
    "gate_index.json",
)


# ③ deterministic regeneration.


def test_all_five_indexes_are_produced(
    packages: list[WorkPackage], registry_document: dict[str, Any]
) -> None:
    """The generator emits exactly the five named indexes."""
    rendered = render_indexes(packages, registry_digest(registry_document))
    assert set(rendered) == set(INDEX_FILENAMES)


def test_same_input_gives_byte_identical_output(registry_document: dict[str, Any]) -> None:
    """Two runs over the same registry produce the same bytes."""
    first = render_indexes(
        group_by_work_package(registry_document), registry_digest(registry_document)
    )
    second = render_indexes(
        group_by_work_package(copy.deepcopy(registry_document)), registry_digest(registry_document)
    )
    assert first == second


def test_one_changed_bit_changes_every_index(registry_document: dict[str, Any]) -> None:
    """A single altered character in the registry changes all five indexes.

    The mutated field (`spec_ref`) is projected by none of the five indexes, so
    this also pins the reason each file carries its source digest: without it
    an index could stay byte identical while its input moved underneath it.
    """
    before = render_indexes(
        group_by_work_package(registry_document), registry_digest(registry_document)
    )

    mutated = copy.deepcopy(registry_document)
    mutated["entries"][0]["spec_ref"] = mutated["entries"][0]["spec_ref"] + "x"
    after = render_indexes(group_by_work_package(mutated), registry_digest(mutated))

    for name in INDEX_FILENAMES:
        assert before[name] != after[name], name


def test_key_insertion_order_does_not_change_output(registry_document: dict[str, Any]) -> None:
    """Reordering the entry list does not change the generated bytes."""
    reordered = copy.deepcopy(registry_document)
    reordered["entries"].reverse()
    assert render_indexes(
        group_by_work_package(reordered), registry_digest(registry_document)
    ) == render_indexes(
        group_by_work_package(registry_document), registry_digest(registry_document)
    )


def test_indexes_declare_the_digest_of_their_source(
    packages: list[WorkPackage], registry_document: dict[str, Any]
) -> None:
    """Every index records the digest of the registry content it came from."""
    digest = registry_digest(registry_document)
    rendered = render_indexes(packages, digest)
    for name in INDEX_FILENAMES:
        assert json.loads(rendered[name])["source_digest"] == digest


# ④ req_index and wp_index are mutual inverses.


def test_real_indexes_are_mutual_inverses(packages: list[WorkPackage]) -> None:
    """The generated pair is inverse in both directions."""
    assert check_index_inverse(build_req_index(packages), build_wp_index(packages)) == []


def test_forward_only_pair_is_rejected() -> None:
    """A requirement mapped forward but not listed back is rejected."""
    req_index = {"FR-AAA-001": "WP-0C-01"}
    wp_index: dict[str, Record] = {
        "WP-0C-01": {"requirements": [], "axes": {}, "contract_refs": []}
    }
    assert check_index_inverse(req_index, wp_index) != []


def test_backward_only_pair_is_rejected() -> None:
    """A requirement listed by a package but absent from req_index is rejected."""
    req_index: dict[str, str] = {}
    wp_index: dict[str, Record] = {
        "WP-0C-01": {"requirements": ["FR-AAA-001"], "axes": {}, "contract_refs": []}
    }
    assert check_index_inverse(req_index, wp_index) != []


def test_crossed_pair_is_rejected() -> None:
    """A requirement claimed by two packages in opposite directions is rejected."""
    req_index = {"FR-AAA-001": "WP-0C-01"}
    wp_index: dict[str, Record] = {
        "WP-0C-01": {"requirements": [], "axes": {}, "contract_refs": []},
        "WP-0C-02": {"requirements": ["FR-AAA-001"], "axes": {}, "contract_refs": []},
    }
    assert check_index_inverse(req_index, wp_index) != []


def test_consistent_pair_is_accepted() -> None:
    """A pair that is inverse in both directions stays green."""
    req_index = {"FR-AAA-001": "WP-0C-01"}
    wp_index: dict[str, Record] = {
        "WP-0C-01": {"requirements": ["FR-AAA-001"], "axes": {}, "contract_refs": []}
    }
    assert check_index_inverse(req_index, wp_index) == []


def test_generation_refuses_a_non_inverse_pair(
    packages: list[WorkPackage], registry_document: dict[str, Any]
) -> None:
    """Rendering aborts rather than emitting a one-directional pair.

    Two packages claiming the same requirement break the inverse: `req_index`
    keeps one mapping while `wp_index` lists the requirement under both.
    """
    donor, receiver = packages[0], packages[1]
    stolen = donor.requirements[0]
    forged = WorkPackage(**{**vars(receiver), "requirements": [*receiver.requirements, stolen]})
    with pytest.raises(ValueError, match="mutual inverses"):
        render_indexes([donor, forged], registry_digest(registry_document))


# Index content.


def test_wp_index_derives_contract_refs(packages: list[WorkPackage]) -> None:
    """contract_refs is exactly consumes union produces, computed not stored."""
    index = build_wp_index(packages)
    for package in packages:
        expected = sorted(set(package.consumes) | set(package.produces))
        assert index[package.wp_id]["contract_refs"] == expected


def test_glob_index_reports_owner_and_mode(packages: list[WorkPackage]) -> None:
    """Every owned glob maps to its owning packages with their ownership mode."""
    index = build_glob_index(packages)
    owned = {entry["glob"] for package in packages for entry in package.stage_owns}
    assert set(index) == owned
    for owners in index.values():
        assert all({"wp", "mode"} == set(owner) for owner in owners)


def test_glob_index_keeps_sequential_handover_visible(packages: list[WorkPackage]) -> None:
    """A glob handed from one package to the next keeps both owners."""
    index = build_glob_index(packages)
    handover = "packages/lerobot_robot_openarm/openarm_follower_oa.py"
    assert len(index[handover]) > 1


def test_contract_index_splits_producer_and_consumers(packages: list[WorkPackage]) -> None:
    """Each contract records its producing and consuming packages separately."""
    index = build_contract_index(packages)
    for contract, sides in index.items():
        for wp_id in sides["producers"]:
            assert contract in _package(packages, wp_id).produces
        for wp_id in sides["consumers"]:
            assert contract in _package(packages, wp_id).consumes


def test_gate_index_walks_descendants_transitively() -> None:
    """Descendants are the full closure, not the first hop.

    A one-hop walk would leave the far side of the chain live on top of a
    superseded measurement, which is the failure `06` §4.4 step 1 exists to
    prevent.
    """
    chain = [
        _stub("WP-0C-01", gates=["PG-J7-001"], downstream=["WP-0C-02"]),
        _stub("WP-0C-02", downstream=["WP-0C-03"]),
        _stub("WP-0C-03", downstream=[]),
    ]
    index = build_gate_index(chain)
    assert index["PG-J7-001"]["work_packages"] == ["WP-0C-01"]
    assert index["PG-J7-001"]["descendants"] == ["WP-0C-02", "WP-0C-03"]


def test_gate_index_seeds_from_stale_triggers() -> None:
    """A package naming a gate as a stale trigger hangs off that gate too."""
    index = build_gate_index(
        [_stub("WP-1-04", gates=[], stale_on=["PG-RT-001b:PASS"], downstream=[])]
    )
    assert index["PG-RT-001b"]["work_packages"] == ["WP-1-04"]


def test_gate_index_terminates_on_a_cycle() -> None:
    """A cycle in downstream does not stall the descendant walk."""
    index = build_gate_index(
        [
            _stub("WP-0C-01", gates=["PG-J7-001"], downstream=["WP-0C-02"]),
            _stub("WP-0C-02", downstream=["WP-0C-01"]),
        ]
    )
    assert index["PG-J7-001"]["descendants"] == ["WP-0C-02"]


def _package(packages: list[WorkPackage], wp_id: str) -> WorkPackage:
    """Look up one package view by id.

    Args:
        packages: Collapsed registry views.
        wp_id: Package id to find.

    Returns:
        WorkPackage: The matching view.
    """
    return next(package for package in packages if package.wp_id == wp_id)


def _stub(
    wp_id: str,
    gates: list[str] | None = None,
    stale_on: list[str] | None = None,
    downstream: list[str] | None = None,
) -> WorkPackage:
    """Build a minimal package view for graph-shape assertions.

    Args:
        wp_id: Package id.
        gates: Gate ids the package declares.
        stale_on: Stale-propagation triggers.
        downstream: Successor ids.

    Returns:
        WorkPackage: A view carrying only the graph axes.
    """
    return WorkPackage(
        wp_id=wp_id,
        requirements=[],
        workflow="SHAPE-IM",
        exec_class="AI-offline",
        phases=None,
        owns=[],
        gates=gates or [],
        consumes=[],
        produces=[],
        stale_on=stale_on or [],
        downstream=downstream or [],
        normalization_hash=None,
        env_hash=None,
        records=[],
    )
