"""IK bench harness — the per-target input to PG-IK-001 (03 §5.11, 05 NFR-TEL-004).

PG-IK-001 is a *per-target* gate: IK latency and the unconstrained-fallback count
split across the heterogeneous fleet (Jetson Nano/Orin, RTX 5090/A6000), so an x86
measurement is not a fleet verdict — NFR-TEL-004 forbids treating one host's numbers
as every target's. This harness is therefore built to run *per target* and to record,
honestly, which target it actually measured on. It fixes no numeric pass/fail
threshold: PG-IK-001 sets those after measurement (WP-0C-04 calibrates the
distribution). The harness produces the runnable input and the raw numbers; the gate
owns the verdict.

Reachable EE targets are generated by a seeded FK round-trip — sample joint configs
inside the overridden soft limits, forward-kinematics them to poses, solve back —
rather than hard-coding a pose, so no numeric target is nailed here either.

On this host the bench measures locally and marks ``measured_on_target=False`` for
every fleet target: this machine is an rtx_5080 (targets/matrix.yaml), not one of the
four, so a faithful per-target number needs that target's hardware. The harness
mirrors the matrix's explicit-deferral honesty instead of relabelling a local number
as a fleet result.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import platform
import time
from collections.abc import Iterator
from dataclasses import asdict, dataclass, field

import numpy as np
from openarm_control.kinematics import IKParams

from sim.ik.adapter import SIDE_WIDTH, IkAdapter, build_ik_adapter
from sim.ik.faults import IkFaultCode
from sim.ik.limits import all_soft_limits
from targets.matrix import FLEET_TARGETS, load_matrix

# Default bench size — enough samples for a p50/p99 shape without making the harness
# slow to run per target. Not a gate parameter; PG-IK-001 chooses its own N.
DEFAULT_SAMPLES = 32
DEFAULT_SEED = 0

# Exact target hosts this bench can natively measure. Empty here: this host matches
# no fleet target exactly (targets/matrix.yaml), so every target is measured-off.
EXACT_TARGET_HOSTS: frozenset[str] = frozenset()


@dataclass(frozen=True)
class BenchResult:
    """One target's bench measurement, tagged with its measurement provenance.

    Attributes:
        target_id: The fleet target this run is labelled for.
        host: The machine the numbers were actually produced on.
        measured_on_target: Whether ``host`` is the labelled target (else the numbers
            are local and the per-target figure remains deferred).
        samples: Number of IK solves timed.
        successes: Solves that returned an accepted action (no HOLD).
        fallback_firings: Total unconstrained-fallback firings across the run.
        latency_ms_p50: Median solve latency in milliseconds, or None when empty.
        latency_ms_p99: p99 solve latency in milliseconds, or None when empty.
        note: Human-readable provenance note (why deferred, if it is).
    """

    target_id: str
    host: str
    measured_on_target: bool
    samples: int
    successes: int
    fallback_firings: int
    latency_ms_p50: float | None
    latency_ms_p99: float | None
    note: str = ""


@dataclass
class BenchRun:
    """A full PG-IK-001 harness run across the fleet.

    Attributes:
        host: The host all measurements were produced on.
        seed: The RNG seed used to generate the FK-round-trip targets.
        results: One ``BenchResult`` per fleet target, in ``FLEET_TARGETS`` order.
    """

    host: str
    seed: int
    results: list[BenchResult] = field(default_factory=list)

    def to_dict(self) -> dict[str, object]:
        """Return a JSON-serialisable view of the run (the PG-IK-001 input record)."""
        return {
            "host": self.host,
            "seed": self.seed,
            "fleet_targets": list(FLEET_TARGETS),
            "results": [asdict(result) for result in self.results],
        }


@contextlib.contextmanager
def _quiet_openarm_control() -> Iterator[None]:
    """Swallow ``openarm_control``'s build-time debug prints (kinematics.py:160-161).

    The vendored solver prints its active-qpos and freeze-dof sets to stdout when a
    ``_IKSolver`` is constructed. That is upstream noise, not this WP's output, and
    it corrupts the harness's JSON on stdout; the library is not ours to edit, so it
    is silenced here at the boundary instead.
    """
    with contextlib.redirect_stdout(io.StringIO()):
        yield


def host_fingerprint() -> str:
    """Return a short label for the machine the bench runs on.

    Returns:
        (str) ``<node>/<machine>/<system>`` — enough to tell whether a run's numbers
        came from a fleet target or a stand-in host.
    """
    return f"{platform.node()}/{platform.machine()}/{platform.system()}"


def _target_arch(target_id: str) -> str:
    """Return a fleet target's declared arch from the matrix, or ``?`` when absent."""
    for target in load_matrix().get("targets", []) or []:
        if str(target.get("target_id", "")) == target_id:
            return str(target.get("arch", "?"))
    return "?"


def sample_reachable_targets(
    adapter: IkAdapter, count: int, seed: int
) -> list[tuple[np.ndarray, np.ndarray]]:
    """Generate reachable (pose_right, pose_left) targets via a seeded FK round-trip.

    Sampling inside the overridden soft limits and forward-kinematicsing keeps every
    target reachable and nails no numeric pose.

    Args:
        adapter: A built adapter (its Kinematics supplies FK).
        count: Number of target pairs to generate.
        seed: RNG seed for reproducibility.

    Returns:
        (list[tuple[np.ndarray, np.ndarray]]) ``count`` (pose_right, pose_left) pairs.
    """
    rng = np.random.default_rng(seed)
    limits = all_soft_limits()
    lower = np.array([limit.lower_rad.value for limit in limits], dtype=float)
    upper = np.array([limit.upper_rad.value for limit in limits], dtype=float)
    kin = adapter._kin

    targets: list[tuple[np.ndarray, np.ndarray]] = []
    for _ in range(count):
        config = lower + rng.random(len(limits)) * (upper - lower)
        right = config[:SIDE_WIDTH]
        left = config[SIDE_WIDTH:]
        pose_right, pose_left = kin.fk_bimanual(right, left)
        targets.append((pose_right.copy(), pose_left.copy()))
    return targets


def run_target_bench(
    target_id: str,
    samples: int = DEFAULT_SAMPLES,
    seed: int = DEFAULT_SEED,
    ik_params: IKParams | None = None,
) -> BenchResult:
    """Run the IK bench for one fleet target and return its measured result.

    The computation is identical for every target — the hardware does not change on
    this host — so the result is tagged with the real host and
    ``measured_on_target``; it never relabels a local number as a fleet figure.

    Args:
        target_id: One of ``FLEET_TARGETS``.
        samples: Number of IK solves to time.
        seed: RNG seed for the FK-round-trip targets.
        ik_params: mink IK parameters; None uses the defaults.

    Returns:
        (BenchResult) The target's measurement with provenance.

    Raises:
        ValueError: When ``target_id`` is not a fleet target.
    """
    if target_id not in FLEET_TARGETS:
        raise ValueError(f"unknown fleet target {target_id!r}; expected one of {FLEET_TARGETS}")

    latencies_ms: list[float] = []
    successes = 0
    fallback_firings = 0
    with _quiet_openarm_control():
        adapter = build_ik_adapter(ik_params=ik_params)
        pairs = sample_reachable_targets(adapter, samples, seed)
        for pose_right, pose_left in pairs:
            adapter.set_target("right", pose_right)
            adapter.set_target("left", pose_left)
            start = time.perf_counter()
            outcome = adapter.solve()
            latencies_ms.append((time.perf_counter() - start) * 1e3)
            if not outcome.held:
                successes += 1
            fallback_firings += sum(
                1 for fault in outcome.faults if fault.code is IkFaultCode.UNCONSTRAINED_FALLBACK
            )

    host = host_fingerprint()
    measured = host in EXACT_TARGET_HOSTS
    note = (
        ""
        if measured
        else f"measured on {host} (arch {platform.machine()}), not target "
        f"{target_id} (arch {_target_arch(target_id)}); per-target figure deferred "
        "(NFR-TEL-004: an x86 number is not a fleet verdict)"
    )
    return BenchResult(
        target_id=target_id,
        host=host,
        measured_on_target=measured,
        samples=len(latencies_ms),
        successes=successes,
        fallback_firings=fallback_firings,
        latency_ms_p50=float(np.percentile(latencies_ms, 50)) if latencies_ms else None,
        latency_ms_p99=float(np.percentile(latencies_ms, 99)) if latencies_ms else None,
        note=note,
    )


def run_all_targets(
    samples: int = DEFAULT_SAMPLES, seed: int = DEFAULT_SEED, ik_params: IKParams | None = None
) -> BenchRun:
    """Run the bench across every fleet target.

    Args:
        samples: Number of IK solves per target.
        seed: RNG seed for the FK-round-trip targets.
        ik_params: mink IK parameters; None uses the defaults.

    Returns:
        (BenchRun) The per-target results, in ``FLEET_TARGETS`` order.
    """
    run = BenchRun(host=host_fingerprint(), seed=seed)
    for target_id in FLEET_TARGETS:
        run.results.append(run_target_bench(target_id, samples, seed, ik_params))
    return run


def main(argv: list[str] | None = None) -> int:
    """Run the bench and print the PG-IK-001 input record as JSON.

    Args:
        argv: CLI arguments; None reads ``sys.argv``.

    Returns:
        (int) 0 always — the harness measures, it does not render a pass/fail verdict.
    """
    parser = argparse.ArgumentParser(description="IK bench harness (PG-IK-001 per-target input).")
    parser.add_argument(
        "--target",
        choices=[*FLEET_TARGETS, "all"],
        default="all",
        help="Fleet target to bench, or 'all' (default).",
    )
    parser.add_argument(
        "--samples", type=int, default=DEFAULT_SAMPLES, help="IK solves per target."
    )
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED, help="FK-round-trip RNG seed.")
    args = parser.parse_args(argv)

    if args.target == "all":
        record: dict[str, object] = run_all_targets(args.samples, args.seed).to_dict()
    else:
        result = run_target_bench(args.target, args.samples, args.seed)
        record = {"host": host_fingerprint(), "seed": args.seed, "results": [asdict(result)]}

    print(json.dumps(record, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
