"""CTR-PRIM@v1 — the single import point for the six shared 3A primitives.

The public surface of the shared-primitive contract. `WP-3A-01`..`WP-3A-05`
(`CTR-CAM`/`CAP`/`TEL`/`WS`/`REC`) import their camera identifier, timestamp
domain, frame-type tag, action shape, queue semantics and error envelope from
here, and must not restate any of them (`02b` §5.0b). The frozen bodies are
`schema.py` and `schema.json` (`CONTRACT_FROZEN`); `redefinition.py` is the
static checker that catches a consumer that forks a primitive anyway.
"""

from __future__ import annotations

from contracts.prim.redefinition import (
    Redefinition,
    check_no_redefinition,
    scan_module,
)
from contracts.prim.schema import (
    ACTION_CONTRACT_ID,
    ACTION_IS_POSITION_ONLY,
    ACTION_POSITION_UNIT,
    AGE_INPUT_ROLE,
    ARM_PREFIXES,
    ARM_SIDES,
    BIMANUAL_ACTION_DIM,
    CAMERA_SLOT_KEY_PATTERN,
    CAPTURE_TS_COLUMN_SUFFIX,
    CLOCK_SOURCE,
    CONSUMED_CONTRACTS,
    CONTRACT_ID,
    DEPTH_KEY_SUFFIX,
    ERROR_CODE_PATTERN,
    ERROR_CONTRACT_ID,
    EXPIRY_JUDGE_ROLE,
    FRAME_TYPE_CHANNELS,
    FRAME_TYPE_DTYPE,
    IMAGE_KEY_PREFIX,
    LEASE_EXPIRY_FIELD,
    LEASE_ISSUED_FIELD,
    OPTIONAL_FRAME_TYPES,
    QUEUE_PROFILES,
    REGISTRY,
    REQUIRED_FRAME_TYPE,
    RESERVED_PRIMITIVE_SYMBOLS,
    SCHEMA_VERSION,
    SIM_NAMESPACE_PREFIX,
    SINGLE_ARM_ACTION_DIM,
    TIMESTAMP_UNIT_NS,
    WS_TAG_SEPARATOR,
    AcceptedPositionAction,
    CameraSlotKey,
    CaptureTimestamp,
    ClockRole,
    Deg,
    DropClassification,
    DropPolicy,
    ErrorCode,
    ErrorEnvelope,
    FrameType,
    OaError,
    PrimitiveRedefinitionError,
    PriorityClass,
    QueueSemantics,
    RequestedPositionAction,
    Severity,
    SyntheticGridTimestamp,
    TimestampDomain,
    arm_slot,
    codes,
    error_envelope,
    is_valid_severity,
    sim_slot,
    slot_from_capture_ts_column,
    slot_from_image_key,
    slot_from_ws_tag,
    verify_expiry_owner,
)

__all__ = [
    "ACTION_CONTRACT_ID",
    "ACTION_IS_POSITION_ONLY",
    "ACTION_POSITION_UNIT",
    "AGE_INPUT_ROLE",
    "ARM_PREFIXES",
    "ARM_SIDES",
    "BIMANUAL_ACTION_DIM",
    "CAMERA_SLOT_KEY_PATTERN",
    "CAPTURE_TS_COLUMN_SUFFIX",
    "CLOCK_SOURCE",
    "CONSUMED_CONTRACTS",
    "CONTRACT_ID",
    "DEPTH_KEY_SUFFIX",
    "ERROR_CODE_PATTERN",
    "ERROR_CONTRACT_ID",
    "EXPIRY_JUDGE_ROLE",
    "FRAME_TYPE_CHANNELS",
    "FRAME_TYPE_DTYPE",
    "IMAGE_KEY_PREFIX",
    "LEASE_EXPIRY_FIELD",
    "LEASE_ISSUED_FIELD",
    "OPTIONAL_FRAME_TYPES",
    "QUEUE_PROFILES",
    "REGISTRY",
    "REQUIRED_FRAME_TYPE",
    "RESERVED_PRIMITIVE_SYMBOLS",
    "SCHEMA_VERSION",
    "SIM_NAMESPACE_PREFIX",
    "SINGLE_ARM_ACTION_DIM",
    "TIMESTAMP_UNIT_NS",
    "WS_TAG_SEPARATOR",
    "AcceptedPositionAction",
    "CameraSlotKey",
    "CaptureTimestamp",
    "ClockRole",
    "Deg",
    "DropClassification",
    "DropPolicy",
    "ErrorCode",
    "ErrorEnvelope",
    "FrameType",
    "OaError",
    "PriorityClass",
    "PrimitiveRedefinitionError",
    "QueueSemantics",
    "Redefinition",
    "RequestedPositionAction",
    "Severity",
    "SyntheticGridTimestamp",
    "TimestampDomain",
    "arm_slot",
    "check_no_redefinition",
    "codes",
    "error_envelope",
    "is_valid_severity",
    "scan_module",
    "sim_slot",
    "slot_from_capture_ts_column",
    "slot_from_image_key",
    "slot_from_ws_tag",
    "verify_expiry_owner",
]
