"""The committed provisional friction table exists, is current, and carries every acceptance.

`backend/friction/friction.provisional.yaml` is generated by the CLI. Like `registry/build`, it
must stay in sync with its generator, so the drift guard regenerates in memory and compares.
Parsing it also confirms the one file carries all four acceptances plus the provisional status.
"""

from __future__ import annotations

from typing import Any

import yaml

from backend.friction.cli import DEFAULT_OUTPUT, main, render_provisional_text


def _artifact() -> dict[str, Any]:
    return yaml.safe_load(DEFAULT_OUTPUT.read_text(encoding="utf-8"))


def test_artifact_exists() -> None:
    assert DEFAULT_OUTPUT.is_file()


def test_artifact_is_not_stale() -> None:
    # Byte-for-byte drift guard against the deterministic generator.
    assert DEFAULT_OUTPUT.read_text(encoding="utf-8") == render_provisional_text()


def test_check_mode_passes() -> None:
    assert main(["--check"]) == 0


def test_artifact_carries_every_acceptance() -> None:
    document = _artifact()
    # ② convention, ③ band, ④ seed comparison, ① per-joint fits, and the provisional status.
    assert document["k_convention"]["scale"] == 0.1
    assert document["identification_band"]["log_freq_hz"] == 1000.0
    assert len(document["seed_comparison"]["joints"]) == 7
    assert len(document["joints"]) == 7
    assert all(row["converged"] for row in document["joints"])
    assert document["status"]["pg_fric_001"] == "NOT_PASSED_DEFERRED_TO_HARDWARE"


def test_artifact_filename_marks_it_provisional() -> None:
    assert ".provisional." in DEFAULT_OUTPUT.name
