"""Regenerate `registry/build/**`, or prove that what is on disk matches.

`registry/build/**` is `GENERATED` (`06` §3.3): neither a person nor a
workflow may edit it. `--check` is what makes that mode enforceable rather than
merely declared — it regenerates into memory and reports any file whose bytes
differ from the fresh output, which is the same signal for a hand edit, a stale
generation and a tampered artefact.

Only this package's own outputs are compared. `registry/build/` also holds
artefacts owned by other bootstrap packages (`reconciliation.md` from
`WP-BOOT-01`, the `evidence/<CG-id>/` trees `CI-04b` requires), and deleting or
flagging those would make one generator the judge of another's output.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from registry.generate.indexes import render_indexes
from registry.generate.manifests import MANIFEST_SUBDIR, render_manifests
from registry.generate.source import (
    BUILD_DIR,
    REGISTRY_PATH,
    group_by_work_package,
    load_registry,
    registry_digest,
)

INDEX_FILENAMES = (
    "req_index.json",
    "wp_index.json",
    "glob_index.json",
    "contract_index.json",
    "gate_index.json",
)


def render_all(registry_path: Path) -> dict[str, str]:
    """Generate every owned artefact as build-relative path to file text.

    Args:
        registry_path: Path to `registry/traceability.yaml`.

    Returns:
        dict[str, str]: Build-relative path to file content.
    """
    document = load_registry(registry_path)
    packages = group_by_work_package(document)
    rendered = render_manifests(packages)
    rendered.update(render_indexes(packages, registry_digest(document)))
    return rendered


def owned_paths(build_dir: Path) -> set[str]:
    """List the build-relative paths this generator claims on disk.

    Args:
        build_dir: Root of the generated tree.

    Returns:
        set[str]: Build-relative paths that exist and belong to this generator.
    """
    present = {name for name in INDEX_FILENAMES if (build_dir / name).is_file()}
    manifest_dir = build_dir / MANIFEST_SUBDIR
    if manifest_dir.is_dir():
        present.update(f"{MANIFEST_SUBDIR}/{path.name}" for path in manifest_dir.glob("*.json"))
    return present


def write(build_dir: Path, rendered: dict[str, str]) -> list[str]:
    """Write the generated tree, removing artefacts no longer generated.

    Args:
        build_dir: Root of the generated tree.
        rendered: Build-relative path to file content.

    Returns:
        list[str]: Build-relative paths that were removed as no longer owned.
    """
    for relative, content in rendered.items():
        target = build_dir / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    removed = sorted(owned_paths(build_dir) - set(rendered))
    for relative in removed:
        (build_dir / relative).unlink()
    return removed


def check(build_dir: Path, rendered: dict[str, str]) -> list[str]:
    """Compare the on-disk tree against freshly generated output.

    Args:
        build_dir: Root of the generated tree.
        rendered: Build-relative path to file content.

    Returns:
        list[str]: One message per divergence; empty when the tree is current.
    """
    findings: list[str] = []
    for relative in sorted(rendered):
        target = build_dir / relative
        if not target.is_file():
            findings.append(f"missing: {relative}")
        elif target.read_text(encoding="utf-8") != rendered[relative]:
            findings.append(f"differs from generated output: {relative}")
    findings.extend(
        f"not generated by the current registry: {relative}"
        for relative in sorted(owned_paths(build_dir) - set(rendered))
    )
    return findings


def main(argv: list[str] | None = None) -> int:
    """Run the generator.

    Args:
        argv: Command-line arguments; `sys.argv[1:]` when None.

    Returns:
        int: 0 on success, 1 when `--check` found a divergence.
    """
    parser = argparse.ArgumentParser(prog="oa-index", description=__doc__)
    parser.add_argument("--registry", type=Path, default=REGISTRY_PATH)
    parser.add_argument("--build-dir", type=Path, default=BUILD_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare the tree against fresh output instead of writing it",
    )
    args = parser.parse_args(argv)

    rendered = render_all(args.registry)

    if args.check:
        findings = check(args.build_dir, rendered)
        for finding in findings:
            print(finding, file=sys.stderr)
        if findings:
            print(
                f"{len(findings)} generated file(s) diverge from {args.registry}; "
                "run oa-index to regenerate",
                file=sys.stderr,
            )
            return 1
        print(f"{len(rendered)} generated file(s) match {args.registry}")
        return 0

    removed = write(args.build_dir, rendered)
    for relative in removed:
        print(f"removed: {relative}")
    print(f"wrote {len(rendered)} file(s) under {args.build_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
