"""CTR-TEL@v1 — the teleoperator plugin contract, consuming CTR-PRIM@v1.

The public surface of the teleoperator contract (`02b` §5.2 WP-3A-03). It exposes
the LeRobot-plugin registration facts, the flat `action_features` convention and its
dataset-feature failure surface, the position-only action keyset consumed from
`CTR-PRIM@v1`, the three-level tracking validity, the non-abstract `sync_state`
operational-path rule, the dual-timestamp sample, and the reserved zero-CAN KER slot.

`schema` is the frozen body (mirrored to `contracts/teleop/schema.json` and frozen by
`WP-3A-06`); `static_checks` holds the non-blocking and no-redefinition scanners
(`EXCLUSIVE` machinery, reusing the frozen `CTR-PRIM` scanner); `reverify` renders the
frozen mirror and is the drift hook. Nothing here imports the robot stack, so the whole
contract runs in the AI-offline light lane.
"""

from __future__ import annotations

from contracts.teleop.reverify import (
    FROZEN_MIRROR_PATH,
    OWNER_WP,
    ReverifyResult,
    frozen_schema,
    render_frozen_json,
    reverify,
)
from contracts.teleop.schema import (
    ABSTRACT_MEMBERS,
    CONFIG_CLASS_SUFFIX,
    CONSUMED_CONTRACTS,
    CONTRACT_ID,
    FEATURE_CONVENTION_FLAT,
    FEATURE_CONVENTION_NESTED,
    FEEDBACK_FEATURES,
    KER_CAN_CHANNELS,
    KER_DIST_NAME,
    KER_PERFORMS_IK,
    KER_TELEOP_TYPE,
    KER_TRANSPORT,
    KER_USB_PID,
    KER_USB_VID,
    NESTED_FEATURE_KEYS,
    POSITION_SUFFIX,
    RECEIVE_TS_ROLE,
    SCHEMA_VERSION,
    SOURCE_TS_ROLE,
    SYNC_STATE_METHOD,
    TELEOPERATOR_DIST_PREFIX,
    TORQUE_SUFFIX,
    VALIDITY_ERROR_CODES,
    VELOCITY_SUFFIX,
    VR_CONFIG_CLASS,
    VR_DEVICE_CLASS,
    VR_DIST_NAME,
    VR_TELEOP_TYPE,
    ZERO_NON_POSITION_VALUE,
    FeatureConventionError,
    KerContractError,
    KerInsertionSlot,
    OpenLoopOperationalError,
    OperationalPath,
    PluginConventionError,
    TeleopSample,
    TeleopValidity,
    aggregate_dataset_action_features,
    device_class_from_config_class,
    feature_convention,
    is_action_dim_position_only,
    is_flat_action_features,
    is_plugin_convention_compliant,
    position_key_count,
    require_plugin_convention,
    require_sync_state_on_operational,
    reserved_ker_slot,
    validity_envelope,
    verify_ker_consumes_zero_can,
    verify_non_position_dims_zero,
    verify_source_is_age_input,
)
from contracts.teleop.static_checks import (
    BLOCKING_CALL_NAMES,
    NON_BLOCKING_METHOD,
    TELEOP_CONTRACT_FILES,
    BlockingCall,
    get_action_is_non_blocking,
    scan_blocking_io,
    scan_teleop_redefinitions,
)

__all__ = [
    "ABSTRACT_MEMBERS",
    "BLOCKING_CALL_NAMES",
    "CONFIG_CLASS_SUFFIX",
    "CONSUMED_CONTRACTS",
    "CONTRACT_ID",
    "FEATURE_CONVENTION_FLAT",
    "FEATURE_CONVENTION_NESTED",
    "FEEDBACK_FEATURES",
    "FROZEN_MIRROR_PATH",
    "KER_CAN_CHANNELS",
    "KER_DIST_NAME",
    "KER_PERFORMS_IK",
    "KER_TELEOP_TYPE",
    "KER_TRANSPORT",
    "KER_USB_PID",
    "KER_USB_VID",
    "NESTED_FEATURE_KEYS",
    "NON_BLOCKING_METHOD",
    "OWNER_WP",
    "POSITION_SUFFIX",
    "RECEIVE_TS_ROLE",
    "SCHEMA_VERSION",
    "SOURCE_TS_ROLE",
    "SYNC_STATE_METHOD",
    "TELEOPERATOR_DIST_PREFIX",
    "TELEOP_CONTRACT_FILES",
    "TORQUE_SUFFIX",
    "VALIDITY_ERROR_CODES",
    "VELOCITY_SUFFIX",
    "VR_CONFIG_CLASS",
    "VR_DEVICE_CLASS",
    "VR_DIST_NAME",
    "VR_TELEOP_TYPE",
    "ZERO_NON_POSITION_VALUE",
    "BlockingCall",
    "FeatureConventionError",
    "KerContractError",
    "KerInsertionSlot",
    "OpenLoopOperationalError",
    "OperationalPath",
    "PluginConventionError",
    "ReverifyResult",
    "TeleopSample",
    "TeleopValidity",
    "aggregate_dataset_action_features",
    "device_class_from_config_class",
    "feature_convention",
    "frozen_schema",
    "get_action_is_non_blocking",
    "is_action_dim_position_only",
    "is_flat_action_features",
    "is_plugin_convention_compliant",
    "position_key_count",
    "render_frozen_json",
    "require_plugin_convention",
    "require_sync_state_on_operational",
    "reserved_ker_slot",
    "reverify",
    "scan_blocking_io",
    "scan_teleop_redefinitions",
    "validity_envelope",
    "verify_ker_consumes_zero_can",
    "verify_non_position_dims_zero",
    "verify_source_is_age_input",
]
