"""CTR-WS@v1 — the single import point for the WebSocket envelope contract.

The public surface of the single-WebSocket transport (`02b` §5.2 WP-3A-04). It
consumes `CTR-PRIM@v1` and redefines none of its primitives, and it transports the
`WP-2A-02` dead-man lease without redefining its semantics. The frozen body is
`envelope.schema.json` (`CONTRACT_FROZEN`, frozen by `WP-3A-06`); `schema.py` is the
typed mirror consumers import; `redefinition.py` catches a fork of a primitive or
of the lease canon; `reverify.py` proves the JSON, the mirror and `CTR-PRIM@v1` agree.
"""

from __future__ import annotations

from contracts.ws.redefinition import (
    RESERVED_LEASE_SEMANTICS_SYMBOLS,
    Redefinition,
    check_ws_no_redefinition,
)
from contracts.ws.reverify import ReverifyReport, reverify, reverify_body
from contracts.ws.schema import (
    BACKPRESSURE_DROP_FRAMES,
    BACKPRESSURE_PROTECTED_FRAMES,
    BUFFERED_AMOUNT_THRESHOLD_BYTES,
    CLIENT_LEASE_FRAMES,
    CONSUMED_CONTRACTS,
    CONTRACT_DESCRIPTION,
    CONTRACT_ID,
    CONTRACT_TITLE,
    CONTROL_HOLDER_ROLE,
    FORBIDDEN_PARALLEL_STACKS,
    FRAME_TABLE,
    LEASE_GENERATION_CANON_FIELD,
    LEASE_GENERATION_FIELD,
    LEASE_REASON_FIELD,
    LEASE_SEQUENCE_FIELD,
    LEASE_SESSION_FIELD,
    MAX_LEASE_AGE_FIELD,
    PUBLIC_HEALTH_FORBIDDEN_FIELDS,
    REALTIME_CHANNEL,
    REARM_HANDSHAKE_FRAMES,
    SCHEMA_VERSION,
    WILDCARD_ORIGIN,
    WS_PLAINTEXT_SCHEME,
    WS_SECURE_SCHEME,
    FrameDirection,
    FramePayload,
    FrameSpec,
    LeaseRejectReason,
    WsError,
    WsFrameType,
    WsRole,
    WsSecurityPolicy,
    assert_expiry_owner_is_server,
    authorize_send,
    camera_frame_tag,
    canonical_envelope,
    client_lease_frames_omit_expiry,
    envelope_json,
    health_leaks,
    public_health,
    should_drop_under_backpressure,
    slot_from_camera_frame_tag,
)

__all__ = [
    "BACKPRESSURE_DROP_FRAMES",
    "BACKPRESSURE_PROTECTED_FRAMES",
    "BUFFERED_AMOUNT_THRESHOLD_BYTES",
    "CLIENT_LEASE_FRAMES",
    "CONSUMED_CONTRACTS",
    "CONTRACT_DESCRIPTION",
    "CONTRACT_ID",
    "CONTRACT_TITLE",
    "CONTROL_HOLDER_ROLE",
    "FORBIDDEN_PARALLEL_STACKS",
    "FRAME_TABLE",
    "LEASE_GENERATION_CANON_FIELD",
    "LEASE_GENERATION_FIELD",
    "LEASE_REASON_FIELD",
    "LEASE_SEQUENCE_FIELD",
    "LEASE_SESSION_FIELD",
    "MAX_LEASE_AGE_FIELD",
    "PUBLIC_HEALTH_FORBIDDEN_FIELDS",
    "REALTIME_CHANNEL",
    "REARM_HANDSHAKE_FRAMES",
    "RESERVED_LEASE_SEMANTICS_SYMBOLS",
    "SCHEMA_VERSION",
    "WILDCARD_ORIGIN",
    "WS_PLAINTEXT_SCHEME",
    "WS_SECURE_SCHEME",
    "FrameDirection",
    "FramePayload",
    "FrameSpec",
    "LeaseRejectReason",
    "Redefinition",
    "ReverifyReport",
    "WsError",
    "WsFrameType",
    "WsRole",
    "WsSecurityPolicy",
    "assert_expiry_owner_is_server",
    "authorize_send",
    "camera_frame_tag",
    "canonical_envelope",
    "check_ws_no_redefinition",
    "client_lease_frames_omit_expiry",
    "envelope_json",
    "health_leaks",
    "public_health",
    "reverify",
    "reverify_body",
    "should_drop_under_backpressure",
    "slot_from_camera_frame_tag",
]
